### ISSUE TITLE
Unsupported query in DatabaseIntrospection.get_constraints()

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach-django#10]
The query that Django uses to introspect indexes is unsupported:
```
SELECT
    indexname, array_agg(attname ORDER BY arridx), indisunique, indisprimary,
    array_agg(ordering ORDER BY arridx), amname, exprdef, s2.attoptions
FROM (
    SELECT
        c2.relname as indexname, idx.*, attr.attname, am.amname,
        CASE
            WHEN idx.indexprs IS NOT NULL THEN
                pg_get_indexdef(idx.indexrelid)
        END AS exprdef,
        CASE am.amname
            WHEN 'btree' THEN
                CASE (option & 1)
                    WHEN 1 THEN 'DESC' ELSE 'ASC'
                END
        END as ordering,
        c2.reloptions as attoptions
    FROM (
        SELECT *
        FROM pg_index i, unnest(i.indkey, i.indoption) WITH ORDINALITY koi(key, option, arridx)
    ) idx
    LEFT JOIN pg_class c ON idx.indrelid = c.oid
    LEFT JOIN pg_class c2 ON idx.indexrelid = c2.oid
    LEFT JOIN pg_am am ON c2.relam = am.oid
    LEFT JOIN pg_attribute attr ON attr.attrelid = c.oid AND attr.attnum = idx.key
    WHERE c.relname = %s
) s2
GROUP BY indexname, indisunique, indisprimary, amname, exprdef, attoptions;
```

```
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.FeatureNotSupported: syntax error: unimplemented: unimplemented at or near ")"
DETAIL:  source SQL:
SELECT
                indexname, array_agg(attname ORDER BY arridx), indisunique, indisprimary,
                                                            ^
HINT:  See: https://github.com/cockroachdb/cockroach/issues/23620
```
It's unclear to me if there's an outstanding cockroachdb issue that'll allow this or if an alternate query must be written. The hint issue (https://github.com/cockroachdb/cockroach/issues/23620) is closed.

**Comment by jordanlewis** [comment]
What version of CockroachDB are you on? This should be supported in the 19.2 branch. https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20190930.html

**Comment by jordanlewis** [comment]
Ah, we don't support that form of `unnest` (two array input). We can probably just add support for that. I'll file an issue.

**Comment by timgraham** [comment]
I didn't write the SQL in question so I'm not sure if I can help but could you describe the issue in words?

**Comment by jordanlewis** [comment]
Well, I don't understand the issue yet. `unnest` is normally a function that returns one row per element in an array. This form of `unnest` seems to take 2 arguments, and yet in Postgres you can't call it as an ordinary function - you have to use it in the `FROM` clause.

I was looking at some old documentation before, but it does appear to be documented as of Postgres 9: https://www.postgresql.org/docs/9.6/functions-array.html

**Comment by rohany** [comment]
I ran into the two array unnest alot while working through the test suite. But those could be due to this failing metadata query.

**Comment by timgraham** [comment]
Yes, this query originates from Django's testing machinery.

**Comment by timgraham** [comment]
A workaround for until the cockroachdb issue is addressed is https://github.com/cockroachdb/cockroach-django/pull/62.
